name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'End-to-end tests' ]                     # runs after 'End-to-end tests' workflow
    types:
      - completed
jobs:
  report:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          node-version: 16
          artifact: test-results            # artifact name
          name: Tests Result                # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results